<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0mkj90c\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0mkj90c/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0mkj90c.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0mkj90c\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0mkj90c\appProdProjectContainer(array(
    'container.build_hash' => '0mkj90c',
    'container.build_id' => '3894fbdc',
    'container.build_time' => 1518718634,
));
