<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrfiuuc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrfiuuc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDrfiuuc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDrfiuuc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDrfiuuc\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Drfiuuc',
    'container.build_id' => '95399b2a',
    'container.build_time' => 1519101469,
));
