<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYc8ansx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYc8ansx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYc8ansx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYc8ansx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYc8ansx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Yc8ansx',
    'container.build_id' => '5a1c25ad',
    'container.build_time' => 1518993560,
));
