<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4hak9x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4hak9x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX4hak9x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX4hak9x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX4hak9x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'X4hak9x',
    'container.build_id' => '04e25b79',
    'container.build_time' => 1519075956,
));
